// <auto-generated />
using CarparkInfoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarparkInfoAPI.Migrations
{
    [DbContext(typeof(CarparkDbContext))]
    partial class CarparkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("CarparkInfoAPI.Models.Carpark", b =>
                {
                    b.Property<string>("car_park_no")
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("car_park_basement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("car_park_decks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("car_park_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("free_parking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("gantry_height")
                        .HasColumnType("REAL");

                    b.Property<bool>("night_parking")
                        .HasColumnType("INTEGER");

                    b.Property<string>("short_term_parking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type_of_parking_system")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("x_coord")
                        .HasColumnType("REAL");

                    b.Property<float>("y_coord")
                        .HasColumnType("REAL");

                    b.HasKey("car_park_no");

                    b.ToTable("Carparks");
                });

            modelBuilder.Entity("CarparkInfoAPI.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarparkInfoAPI.Models.UserFavourite", b =>
                {
                    b.Property<int>("user_favourite_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("car_park_no")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("user_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("user_favourite_id");

                    b.ToTable("UserFavourites");
                });
#pragma warning restore 612, 618
        }
    }
}
